### ISSUE TITLE
Schematic ideas

### ISSUE THREAD

**Issue by electroniceel** [attie/glasgow-can#1]
Here are some ideas from me for improving the schematic:

### Reduce to one Glasgow port

Your current design uses both Glasgow ports. For core functions you only need 4 pins of Glasgow per CAN bus (TX, RX, Silent, Term). So you could reduce the design to one port of Glasgow. You could even leave the Silent pin open, as I don't see any advantage of using it in this application. It just blocks the TX input on the receiver. Since both pins are controlled by Glasgow gateware, I don't really see the point of using it.

For the TX/RX LEDs you could either directly connect the LEDs on your addon to the TX and RX lines. If you fear that you don't see the LEDs light up on short transmission pulses, you could prolong each LED pulse with a 74LVC2G14 and a small RC delay between the two gates (can draw you a schematic if this isn't clear enough, just ask). Alternatively you could use the user LEDs of Glasgow.

Here are some feature ideas that would make use of the second port on Glasgow:
- Debugging a CAN-enabled microcontroller, JTAG is on the other port of Glasgow
- Industrial control protocol translator: CAN on one side, RS485 Modbus on the other (RS485 addon on the other port)
- translating CAN switch with 4 CAN busses (a second CAN addon on the other port)

The current Glasgow software doesn't support multiple applets running in parallel yet. But this is something that whitequark definitely has planned for the future.

### Term LED

Add a LED to show if the termination is enabled.

### Notice

Just to clarify: this is your project and I don't want to interfere. Feel free to ignore all this and close this issue, no hard feelings from my side.

**Comment by attie** [comment]
Hi! Thanks very much for taking the time to have a look and leave your feedback / ideas, I really appreciate it.

### Reduce to one Glasgow port

I agree that the Silent signal is fairly redundant here, given that we control the gateware... My previous application of this transceiver had to be quite strict on when bus activity was permitted, and the controller wasn't necessarily to be trusted - so it's a bit of a hangover from that.

Therefore, I totally agree that it's possible to reduce the signals for each interface to Tx/Rx/Term, and hang LEDs off each of these.

This also throws up an interesting point - I don't think _any_ other Glasgow applets have facility for status LEDs... and I don't think I've come across one that uses the user LEDs either. So providing these LEDs may not fit well... I asked in `#glasgow`, and whitequark seems to agree.

My initial thinking for the Tx/Rx LEDs being controlled from gateware was that we could potentially ensure that the frame was valid, or only blink the LED when a received frame matched a filter... I'm no longer convinved this is really that useful (it may actually be actively misleading), and the Tx LED certainly doesn't require its own signal... so yeah, why not drop the dedicated LED signals and drive from the Tx/Rx signals directly. I'm happy to wire up an RC delay, and 74LVC2G14 is a good call.

I had planned to put one CAN interface on each port - so that it's a matter of specifying either A or B depending on the physical connector you want, rather than picking out the specific pin numbers... but also thinking forward to when multiple applets are supported - e.g: if there's an unfortunate limitation that each applet takes a whole port, then we're still set... again, discussed in `#glasgow`, and I think this point is moot (yay).

### 2x CAN Interfaces

I like having two CAN interfaces, as it would be possible to produce a full CAN-to-CAN loopback test with one unit, but I'm starting to wonder if it's really neccessary... there's no good reason to not give both DE-9 and Spring Terminals on one interface, and drop the second - the stubs at this speed aren't a problem for signal integrity...

I'd like to keep two interfaces, but would also appreciate your thoughts on the matter.

I also like having DE-9 _and_ Spring Terminals, as it gives flexibility.

### Term LED

Great idea - I'll add that, thanks!

---

### Todo

_Moved to latest message._

**Comment by electroniceel** [comment]
> My initial thinking for the Tx/Rx LEDs being controlled from gateware was that we could potentially ensure that the frame was valid, or only blink the LED when a received frame matched a filter... I'm no longer convinved this is really that useful (it may actually be actively misleading),

I think LEDs showing any kind of activity on the bus make more sense, not just error-free received frames. If you want to distinguish errors, I suggest to add a dedicated "frame error" LED that just lights up in cases of errors. This makes them more obvious. You could either use the user LEDs on Glasgow for this or use the port pin you previously planned for silent.

>  I'm happy to wire up an RC delay, and 74LVC2G14 is a good call.

I was a bit sloppy in my description, you'll also need a diode in parallel to the resistor, to let the voltage on the C rise fast, but discharge slowly. A basic RC without diode would just delay lighting the LED, not prolong it.

> ### 2x CAN Interfaces
> 
> I like having two CAN interfaces, as it would be possible to produce a full CAN-to-CAN loopback test with one unit, but I'm starting to wonder if it's really neccessary...

I strongly suggest to implement two CAN interfaces. Because for reverse engineering CAN it is a very common technique to isolate a device to it's own dedicated bus to see which kinds of messages are emitted by it and then selectively route messages between the dedicated bus and the one the device is usually connected to. Also live patching of messages can be a helpful tool. Glasgow with it's FPGA is a perfect tool for this, because it would allow this routing and patching to happen in real time in gateware.

If someone is concerned by the extra cost of the second transceiver, they can just leave it unpopulated.

> I also like having DE-9 _and_ Spring Terminals, as it gives flexibility.

I haven't taken a close look at component sizes or board layout. But from a usability standpoint having spring terminals and DE-9 each for both interfaces would be best. When you go to just one port on Glasgow, plugging in such a huge addon could become a mechanical problem. You could change to a short ribbon cable for connecting to Glasgow and place the CAN addon next to it instead of above.

Edit: when reading your todo item "Add a 0.1" pins to port B, or a shrouded 2x10 header" it sounds to me like you still plan to plug your addon into both ports, for mechanical stability. But then offer a shrouded header for other stuff to be plugged into the addon. I think this is not equivalent to using the port directly on Glasgow:
- You probably won't be able to use two of your CAN addons at the same time (think isolating two can devices in their own bus at the same time or a 4 bus switch)
- revD Glasgows will keep the same distance for the port headers, but add extra pin headers (probably female, for touch protection) for addon communication. If you recreate the other port header on your addon, you won't have that interface.

**Comment by attie** [comment]
> I think LEDs showing any kind of activity on the bus make more sense, not just error-free received frames. [...] You could either use the user LEDs on Glasgow for this or use the port pin you previously planned for silent.

Agreed

> I was a bit sloppy in my description, you'll also need a diode in parallel to the resistor, to let the voltage on the C rise fast, but discharge slowly. A basic RC without diode would just delay lighting the LED, not prolong it.

Yep!

> I strongly suggest to implement two CAN interfaces. Because for reverse engineering CAN it is a very common technique to isolate a device to it's own dedicated bus to see which kinds of messages are emitted by it and then selectively route messages between the dedicated bus and the one the device is usually connected to.

This is a very good point, and a use-case that I'd thought of, but couldn't recall when asked the other day... I'll put it in the readme when I get a chance - thanks!

> Also live patching of messages can be a helpful tool.

This also sounds like a neat idea!

> I haven't taken a close look at component sizes or board layout. But from a usability standpoint having spring terminals and DE-9 each for both interfaces would be best.

I agree that both connectors for both interfaces would be ideal... the major issue is space for two DE-9 connectors.

> You could change to a short ribbon cable for connecting to Glasgow and place the CAN addon next to it instead of above.
> Edit: when reading your todo item "Add a 0.1" pins to port B, or a shrouded 2x10 header" it sounds to me like you still plan to plug your addon into both ports, for mechanical stability.

This is an interesting idea, and will address the space issue directly. I had indeed hoped to produce a top-mounted add-on, but I'm certainly open to a "1-port, 2x CAN" addon, that connects with a ribbon... in fact, this might be preferred - as you suggest, it would be possible to use 2x CAN add-ons at once, for 4x CAN interfaces...

---

### Todo

- [x] Remove Silent LED
- [x] Move Tx/Rx LEDs to transceiver signals (and off dedicated signals)
- [x] Reduce channel signals to Tx/Rx/Term
- [x] Add a Termination LED
- [x] Wire both CAN interface signals to a single Glasgow port
- [x] Revise to use a single Glasgow port (via a Ribbon), and sit alongside, instead of on top
- [x] Revise so that both interfaces have DE-9 _and_ spring terminals

**Comment by electroniceel** [comment]
> I agree that both connectors for both interfaces would be ideal... the major issue is space for two DE-9 connectors.

If you still want to continue the addon-on-top approach, you could stack two boards to get more usable space: a lower board, with the connector to Glasgow and the transceivers. Pin headers for CAN-H, CAN-L, GND and the LEDs. Then a board that is screwed on top, with the spring loaded terminals, DE-9 and the leds.

I can see the appeal of putting everything on top of Glasgow, but also the ease of placing all connectors on a basic PCB when you use the external ribbon-connected PCB. So I'm a bit torn between both solutions here.

**Comment by attie** [comment]
Thes points have now been addressed, thanks very much for your feedback!
